name: voices_unheard
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.3
  share_plus: ^10.1.4
  intl: ^0.20.2
  image_picker: ^1.1.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png

fflutter_native_splash:
  color: "#333333"  # Deep Purple background
  image: "assets/app_logo.png"
  image_mode: "contain"  # Ensures the full logo is visible

  android_12:
    color: "#4B0082"
    image: "assets/app_logo.png"
    image_mode: "contain"

  ios: true
  web: false
  android: true
